added an error

diff --git a/.github/workflows/whatever.yml b/.github/workflows/whatever.yml
--- a/.github/workflows/whatever.yml
+++ b/.github/workflows/whatever.yml
@@ -23,3 +23,5 @@ jobs:
 
       - name: Test 🚨
         run: npm test
+      - name: Error
+        run: echo "About to fail" ; exit 1
